// ─── Partner Companies ────────────────────────────────────────────────────────
export const PARTNERS = [
  {
    id: 'uber',
    name: 'Uber',
    ticker: 'UBER',
    logo: '🚗',
    color: '#000000',
    bgColor: '#1a1a1a',
    description: 'Earn $UBER for every ride and Uber Eats order.',
    rewardRate: 0.005, // 0.5% of transaction → fractional share value
    rewardLabel: '$0.01 in $UBER per ride',
    category: 'Transportation',
    apiStatus: 'available',
    connectUrl: 'https://auth.uber.com/oauth2/v2/authorize',
    scopes: ['rides.read', 'eats.read'],
  },
  {
    id: 'peloton',
    name: 'Peloton',
    ticker: 'PTON',
    logo: '🚴',
    color: '#FC3E3E',
    bgColor: '#1a0a0a',
    description: 'Earn $PTON for every ride, run, and workout.',
    rewardRate: 0.10,
    rewardLabel: '$0.10 in $PTON per workout',
    category: 'Fitness',
    apiStatus: 'available',
    connectUrl: 'https://api.onepeloton.com/auth/login',
    scopes: ['workout_stats'],
  },
  {
    id: 'lyft',
    name: 'Lyft',
    ticker: 'LYFT',
    logo: '🩷',
    color: '#FF00BF',
    bgColor: '#1a0011',
    description: 'Earn $LYFT for every ride you take.',
    rewardRate: 0.005,
    rewardLabel: '$0.01 in $LYFT per ride',
    category: 'Transportation',
    apiStatus: 'available',
    connectUrl: 'https://api.lyft.com/oauth/authorize',
    scopes: ['rides.read'],
  },
  {
    id: 'snap',
    name: 'Snapchat',
    ticker: 'SNAP',
    logo: '👻',
    color: '#FFFC00',
    bgColor: '#1a1a00',
    description: 'Earn $SNAP for daily app engagement.',
    rewardRate: 0.001,
    rewardLabel: '$0.001 in $SNAP per active day',
    category: 'Social',
    apiStatus: 'available',
    connectUrl: 'https://accounts.snapchat.com/accounts/oauth2/auth',
    scopes: ['user.read'],
  },
  {
    id: 'netflix',
    name: 'Netflix',
    ticker: 'NFLX',
    logo: '🎬',
    color: '#E50914',
    bgColor: '#1a0000',
    description: 'Earn $NFLX for hours streamed each month.',
    rewardRate: 0.002,
    rewardLabel: '$0.002 per hour streamed',
    category: 'Entertainment',
    apiStatus: 'coming_soon',
    scopes: [],
  },
  {
    id: 'apple',
    name: 'Apple',
    ticker: 'AAPL',
    logo: '🍎',
    color: '#555555',
    bgColor: '#111111',
    description: 'Earn $AAPL for Apple services usage.',
    rewardRate: 0.002,
    rewardLabel: '$0.002 per service day',
    category: 'Technology',
    apiStatus: 'coming_soon',
    scopes: [],
  },
  {
    id: 'stitch_fix',
    name: 'Stitch Fix',
    ticker: 'SFIX',
    logo: '👗',
    color: '#7B68EE',
    bgColor: '#0f0a1a',
    description: 'Earn $SFIX for every fix you keep.',
    rewardRate: 0.01,
    rewardLabel: '1% of order value in $SFIX',
    category: 'Retail',
    apiStatus: 'coming_soon',
    scopes: [],
  },
  {
    id: 'tmobile',
    name: 'T-Mobile',
    ticker: 'TMUS',
    logo: '📱',
    color: '#E20074',
    bgColor: '#1a0010',
    description: 'Earn $TMUS for your monthly plan.',
    rewardRate: 0.005,
    rewardLabel: '$0.005 per plan day',
    category: 'Telecom',
    apiStatus: 'coming_soon',
    scopes: [],
  },
]

// ─── Mock Portfolio Holdings ─────────────────────────────────────────────────
export const MOCK_HOLDINGS = [
  { partnerId: 'uber',    ticker: 'UBER', shares: 0.4821, avgCost: 68.42, currentPrice: 71.30, totalEarned: 34.56 },
  { partnerId: 'peloton', ticker: 'PTON', shares: 1.2340, avgCost: 5.10,  currentPrice: 4.87,  totalEarned: 6.03  },
  { partnerId: 'lyft',    ticker: 'LYFT', shares: 0.7654, avgCost: 16.20, currentPrice: 17.44, totalEarned: 13.34 },
]

// ─── Mock Activity Feed ──────────────────────────────────────────────────────
export const MOCK_ACTIVITY = [
  { id: 1,  date: '2024-03-15', partnerId: 'uber',    type: 'ride',    description: 'Uber ride — Downtown',           earned: 0.51,  shares: 0.0071, ticker: 'UBER' },
  { id: 2,  date: '2024-03-14', partnerId: 'peloton', type: 'workout', description: 'Peloton Cycling — 30 min',        earned: 0.10,  shares: 0.0205, ticker: 'PTON' },
  { id: 3,  date: '2024-03-13', partnerId: 'uber',    type: 'eats',    description: 'Uber Eats — Chipotle',           earned: 0.87,  shares: 0.0122, ticker: 'UBER' },
  { id: 4,  date: '2024-03-13', partnerId: 'lyft',    type: 'ride',    description: 'Lyft ride — Airport',            earned: 1.23,  shares: 0.0705, ticker: 'LYFT' },
  { id: 5,  date: '2024-03-12', partnerId: 'peloton', type: 'workout', description: 'Peloton Strength — 20 min',      earned: 0.10,  shares: 0.0205, ticker: 'PTON' },
  { id: 6,  date: '2024-03-11', partnerId: 'uber',    type: 'ride',    description: 'Uber ride — Office',             earned: 0.42,  shares: 0.0059, ticker: 'UBER' },
  { id: 7,  date: '2024-03-10', partnerId: 'lyft',    type: 'ride',    description: 'Lyft ride — Restaurant',         earned: 0.65,  shares: 0.0373, ticker: 'LYFT' },
  { id: 8,  date: '2024-03-09', partnerId: 'peloton', type: 'workout', description: 'Peloton Yoga — 45 min',          earned: 0.10,  shares: 0.0205, ticker: 'PTON' },
  { id: 9,  date: '2024-03-08', partnerId: 'uber',    type: 'ride',    description: 'Uber ride — Grocery run',        earned: 0.33,  shares: 0.0046, ticker: 'UBER' },
  { id: 10, date: '2024-03-07', partnerId: 'uber',    type: 'eats',    description: 'Uber Eats — Sweetgreen',         earned: 0.72,  shares: 0.0101, ticker: 'UBER' },
]

// ─── Portfolio chart data (30 days) ─────────────────────────────────────────
export const PORTFOLIO_CHART_DATA = [
  { date: 'Feb 14', value: 41.20 },
  { date: 'Feb 15', value: 42.10 },
  { date: 'Feb 16', value: 41.80 },
  { date: 'Feb 17', value: 43.50 },
  { date: 'Feb 18', value: 44.20 },
  { date: 'Feb 19', value: 43.90 },
  { date: 'Feb 20', value: 45.10 },
  { date: 'Feb 21', value: 46.30 },
  { date: 'Feb 22', value: 45.80 },
  { date: 'Feb 23', value: 47.20 },
  { date: 'Feb 24', value: 48.10 },
  { date: 'Feb 25', value: 47.60 },
  { date: 'Feb 26', value: 49.00 },
  { date: 'Feb 27', value: 50.20 },
  { date: 'Feb 28', value: 51.40 },
  { date: 'Mar 01', value: 50.80 },
  { date: 'Mar 02', value: 52.10 },
  { date: 'Mar 03', value: 53.40 },
  { date: 'Mar 04', value: 52.90 },
  { date: 'Mar 05', value: 54.20 },
  { date: 'Mar 06', value: 55.10 },
  { date: 'Mar 07', value: 54.80 },
  { date: 'Mar 08', value: 56.30 },
  { date: 'Mar 09', value: 57.10 },
  { date: 'Mar 10', value: 56.60 },
  { date: 'Mar 11', value: 58.20 },
  { date: 'Mar 12', value: 57.80 },
  { date: 'Mar 13', value: 59.40 },
  { date: 'Mar 14', value: 60.10 },
  { date: 'Mar 15', value: 53.93 },
]
